# Generated by Django 3.2.15 on 2022-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20221015_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_of_creation',
            field=models.DateField(default=None),
        ),
    ]
