# Generated by Django 3.2.15 on 2022-10-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_of_creation',
            field=models.DateField(),
        ),
    ]
