# Generated by Django 3.2.15 on 2022-10-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20221015_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_of_creation',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_of_update',
        ),
    ]
